const colors = [
    "cadetblue",
    "darkgoldenrod",
    "cornflowerblue",
    "darkkhaki",
    "hotpink",
    "gold",
    "chartreuse",
    "blueviolet",
    "crimson",
    "deeppink",
    "forestgreen",
    "orangered",
    "slateblue",
    "teal",
    "yellow",
];